blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog', ArticleListView.as_view(), name='articles_list'),
    path('blog/<int:pk>/', ArticleDetailView.as_view(), name='articles_detail'),
    path('blog/create', ArticleCreateView.as_view(), name='articles_create'),
    path('blog/<int:pk>/update/', ArticleUpdateView.as_view(), name='articles_update'),
    path('blog/<int:pk>/delete/', ArticleDeleteView.as_view(), name='articles_delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mail.urls', namespace='mail')),
                  path('', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail/urls.py
from django.urls import path
from mail.apps import MailConfig
from mail.views import MailListView, MailDetailView, MailCreateView, MailUpdateView, MailDeleteView, ClientListView, \
    ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, MailMessageListView, MailMessageDetailView, \
    MailMessageCreateView, MailMessageUpdateView, MailMessageDeleteView, MailTryListView, HomePage

app_name = MailConfig.name

urlpatterns = [
    path('', HomePage.as_view(), name='index'),
    path('mails', MailListView.as_view(), name='mails_list'),
    path('mail/<int:pk>/', MailDetailView.as_view(), name='mails_detail'),
    path('mail/create/', MailCreateView.as_view(), name='mails_create'),
    path('mail/<int:pk>/update/', MailUpdateView.as_view(), name='mails_update'),
    path('mail/<int:pk>/delete/', MailDeleteView.as_view(), name='mails_delete'),
    path('сlients', ClientListView.as_view(), name='clients_list'),
    path('сlients/<int:pk>/', ClientDetailView.as_view(), name='clients_detail'),
    path('сlients/create/', ClientCreateView.as_view(), name='clients_create'),
    path('сlients/<int:pk>/update/', ClientUpdateView.as_view(), name='clients_update'),
    path('сlients/<int:pk>/delete/', ClientDeleteView.as_view(), name='clients_delete'),
    path('messages', MailMessageListView.as_view(), name='messages_list'),
    path('messages/<int:pk>/', MailMessageDetailView.as_view(), name='messages_detail'),
    path('messages/create/', MailMessageCreateView.as_view(), name='messages_create'),
    path('messages/<int:pk>/update/', MailMessageUpdateView.as_view(), name='messages_update'),
    path('messages/<int:pk>/delete/', MailMessageDeleteView.as_view(), name='messages_delete'),
    path('mailtries', MailTryListView.as_view(), name='mailtry_list'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, ResetPassword, UserUpdateView, UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('reset_password', ResetPassword.as_view(), name='reset_password'),
    path('user_update/', UserUpdateView.as_view(template_name='profile_form.html'), name='user_update'),
    path('login/profile/', UserDetailView.as_view(template_name='profile.html'), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    token = models.CharField(
        max_length=100,
        verbose_name='Token',
        blank=True,
        null=True,
    )
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('can_block_user', 'Can block user')
        ]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from mail.forms import FormStyleMixin
from users.models import User


class UserRegisterForm(FormStyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class UserUpdateForm(FormStyleMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ['email', 'password',]

users/views.py
from django.shortcuts import render

import secrets

from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, TemplateView, UpdateView, DetailView

from users.forms import UserRegisterForm, UserUpdateForm
from users.models import User

from config.settings import EMAIL_HOST_USER


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Привет, перейди по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserDetailView(DetailView):
    model = User

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class ResetPassword(TemplateView):
    def get(self, request):
        return render(request, 'users/reset_password.html')

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        user = get_object_or_404(User, email=email)
        new_password = secrets.token_hex(8)
        user.set_password(new_password)
        user.save()
        send_mail(
            subject='Изменение пароля',
            message=f'Твой новый пароль: {new_password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return redirect(reverse('users:login'))

users/templates/login.html
{% extends 'mail/base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Войти
                </button>
                <a href="{% url 'users:reset_password' %}" class="text-black">Восстановить пароль</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/profile.html
{% extends 'mail/base.html' %}
{% load my_tags %}
{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Сервис рассылок</h1>
            <p class="lead text-body-secondary">Личный кабинет</p>
        </div>
    </div>
</section>
<div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <p class="card-text">{{ object.username }}</p>
                            <p class="card-text">{{ object.email }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'users:user_update' %}" role="button">Редактировать профиль</a>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'mail:clients_list' %}" role="button">Перейти к клиентам</a>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'mail:mails_list' %}" role="button">Перейти к рассылкам</a>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'mail:messages_list' %}" role="button">Перейти к сообщениям рассылок</a>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'mail:mailtry_list' %}" role="button">Посмотреть последние попытки рассылок</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/profile_form.html
{% extends 'mail/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}