blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog', ArticleListView.as_view(), name='articles_list'),
    path('blog/<int:pk>/', ArticleDetailView.as_view(), name='articles_detail'),
    path('blog/create', ArticleCreateView.as_view(), name='articles_create'),
    path('blog/<int:pk>/update/', ArticleUpdateView.as_view(), name='articles_update'),
    path('blog/<int:pk>/delete/', ArticleDeleteView.as_view(), name='articles_delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mail.urls', namespace='mail')),
                  path('', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail/urls.py
from django.urls import path
from mail.apps import MailConfig
from mail.views import MailListView, MailDetailView, MailCreateView, MailUpdateView, MailDeleteView, ClientListView, \
    ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, MailMessageListView, MailMessageDetailView, \
    MailMessageCreateView, MailMessageUpdateView, MailMessageDeleteView, MailTryListView, HomePage

app_name = MailConfig.name

urlpatterns = [
    path('', HomePage.as_view(), name='index'),
    path('mails', MailListView.as_view(), name='mails_list'),
    path('mail/<int:pk>/', MailDetailView.as_view(), name='mails_detail'),
    path('mail/create/', MailCreateView.as_view(), name='mails_create'),
    path('mail/<int:pk>/update/', MailUpdateView.as_view(), name='mails_update'),
    path('mail/<int:pk>/delete/', MailDeleteView.as_view(), name='mails_delete'),
    path('сlients', ClientListView.as_view(), name='clients_list'),
    path('сlients/<int:pk>/', ClientDetailView.as_view(), name='clients_detail'),
    path('сlients/create/', ClientCreateView.as_view(), name='clients_create'),
    path('сlients/<int:pk>/update/', ClientUpdateView.as_view(), name='clients_update'),
    path('сlients/<int:pk>/delete/', ClientDeleteView.as_view(), name='clients_delete'),
    path('messages', MailMessageListView.as_view(), name='messages_list'),
    path('messages/<int:pk>/', MailMessageDetailView.as_view(), name='messages_detail'),
    path('messages/create/', MailMessageCreateView.as_view(), name='messages_create'),
    path('messages/<int:pk>/update/', MailMessageUpdateView.as_view(), name='messages_update'),
    path('messages/<int:pk>/delete/', MailMessageDeleteView.as_view(), name='messages_delete'),
    path('mailtries', MailTryListView.as_view(), name='mailtry_list'),
]

blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name="Заголовок",
        blank=True,
        null=True,
        help_text='Введите заголовок статьи.'
    )
    slug = models.CharField(
        max_length=100,
        verbose_name="slug",
        blank=True,
        null=True,
        help_text='Введите URL статьи.'
    )
    content = models.TextField(
        verbose_name="Содержимое",
        blank=True,
        null=True,
        help_text='Введите статью.'
    )
    preview = models.ImageField(
        upload_to="catalog/image",
        blank=True,
        null=True,
        verbose_name="Превью статьи",
        help_text='Добавьте изображение.'
    )
    created_at = models.DateTimeField(
        verbose_name="Дата создания",
        blank=True,
        null=True
    )
    published = models.BooleanField(
        verbose_name="Опубликована",
        blank=True
    )
    views_counter = models.PositiveIntegerField(
        verbose_name='Счетчик просмотров',
        help_text='Укажите количество просмотров',
        default=0
    )

    def __str__(self):
        # Строковое отображение объекта
        return f"{self.title}"

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import Article


class ArticleListView(ListView):
    model = Article


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class ArticleCreateView(CreateView):
    model = Article
    fields = ('title', 'content', 'preview', 'published')
    success_url = reverse_lazy('blog:articles_list')


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ('title', 'content', 'preview', 'published')
    success_url = reverse_lazy('blog:articles_list')

    def get_success_url(self):
        return reverse('blog:articles_detail', args=[self.kwargs.get('pk')])


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('blog:articles_list')

blog/templates/articles_confirm_delete.html
{% extends 'mail/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить {{ object.title }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a class="btn btn-primary" href="{% url 'catalog:articles_list' %}" role="button">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/articles_detail.html
{% extends 'mail/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ article.preview | media_filter }}">
                        <div class="card-body">
                            <p class="card-text">{{ object.title }}</p>
                            <p class="card-text">Содержимое: {{ object.content }}</p>
                            <p class="card-text">Просмотры: {{ object.views_counter }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'catalog:articles_list' %}" role="button">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/articles_form.html
{% extends 'mail/base_blog.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/articles_list.html
{% extends 'mail/base.html' %}
{% load my_tags %}
{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Блог</h1>
            {% if user.is_authenticated %}
            <p>
                <a class="btn btn-primary" href="{% url 'mail:mails_create' %}" role="button">
                    Создать статью</a>
            </p>
            {% endif %}
        </div>
    </div>
</section>
<div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for article in object_list %}
                {% if article.published %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ article.preview | media_filter }}" class="rounded float-start">
                        <div class="card-body">
                            <p class="card-text">{{ article.title }}</p>
                            <p class="card-text">{{ article.content|truncatechars:100 }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'catalog:articles_detail' article.pk %}" role="button">Посмотреть</a>
                                    <a class="btn btn-primary" href="{% url 'catalog:articles_update' article.pk %}" role="button">Редактировать</a>
                                    <a class="btn btn-primary" href="{% url 'catalog:articles_delete' article.pk %}" role="button">Удалить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}